### ISSUE TITLE
元素ID为 msg.0 无法通过 $("#msg.0") 获取

### ISSUE THREAD

**Issue by wifi-left** [ganxiaozhe/gQuery#1]
如果elementID为msg.0
无法通过$("#msg.0")获取

**Comment by ganxiaozhe** [comment]
元素id名或类名分割时尽量规避使用CSS3选择器符号，gq的选择器是多义的，#msg.0会解析为id=msg,className=0
请使用：msg-0 或 msg_0
（这个“问题”同时存在于 jquery
